---

fabric_name: FCIX

node_type_keys:
  l2vtep:
    type: l2vtep
    connected_endpoints: true
    default_evpn_role: client
    mlag_support: false
    network_services:
      l2: true
      l3: false
    vtep: true
    interface_descriptions:
      connected_endpoints_ethernet_interfaces: templates/ixp_peer_eth_desc.j2
      connected_endpoints_port_channel_interfaces: templates/ixp_peer_po_desc.j2

underlay_p2p_network_summary: 100.65.0.0/16
overlay_lookback_network_summary: 100.64.0.0/24
vtep_loopback_network_summary: 100.64.128.0/24

p2p_uplinks_qos_profile: qprof_fcix_uplink

evpn_ebgp_multihop: 5

l2vtep:
  defaults:
    mlag: false
    loopback_ipv4_pool: 100.64.0.0/24
    vtep_loopback_ipv4_pool: 100.64.128.0/24
    bgp_defaults:
      - no bgp default ipv4-unicast
      - command clear all disabled

  node_groups:
    HEFMT2:
      uplink_ipv4_pool: 100.65.0.0/20
      nodes:
        CORE1.FMT2.FCIX.NET:
          id: 1
          mgmt_ip: 10.44.24.16/24
          bgp_as: 4200000001
          evpn_role: server
        CORE2.FMT2.FCIX.NET:
          id: 2
          mgmt_ip: 10.44.24.17/24
          bgp_as: 4200000002
          uplink_interfaces: [ Ethernet2/1 ]
          uplink_switches: [ CORE1.FMT2.FCIX.NET ]
          uplink_switch_interfaces: [ Ethernet2/1 ]
          evpn_role: server
          evpn_route_servers: [ CORE1.FMT2.FCIX.NET ]
        SW3.FMT2.FCIX.NET:
          id: 3
          mgmt_ip: 10.44.24.15/24
          bgp_as: 4200000003
          uplink_interfaces: [ Ethernet49/1, Ethernet51/1 ]
          uplink_switches: [ CORE1.FMT2.FCIX.NET, CORE2.FMT2.FCIX.NET ]
          uplink_switch_interfaces: [ Ethernet32/1, Ethernet32/1 ]
          uplink_interface_speed: forced 40g
        SW4.FMT2.FCIX.NET:
          id: 4
          mgmt_ip: 10.44.24.18/24
          bgp_as: 4200000004
          uplink_interfaces: [ Ethernet49/1, Ethernet51/1 ]
          uplink_switches: [ CORE1.FMT2.FCIX.NET, CORE2.FMT2.FCIX.NET ]
          uplink_switch_interfaces: [ Ethernet30/1, Ethernet30/1 ]
          uplink_interface_speed: forced 40g
        SW5.FMT2.FCIX.NET:
          id: 5
          mgmt_ip: 10.44.24.19/24
          bgp_as: 4200000005
          uplink_interfaces: [ Ethernet49/1, Ethernet51/1 ]
          uplink_switches: [ CORE1.FMT2.FCIX.NET, CORE2.FMT2.FCIX.NET ]
          uplink_switch_interfaces: [ Ethernet28/1, Ethernet28/1 ]
          uplink_interface_speed: forced 40g

errdisable:
  recovery:
    causes:
      - bpduguard
      - link-flap
      - portsec
    interval: 600

access_lists:
  acl-protect-ixp-v4:
    sequence_numbers:
      10: # Mikrotik Discovery Protocol
        action: "deny udp any eq 5678 host 255.255.255.255 eq 5678"
      1000:
        action: "ip permit any any"
  acl-bcp214-v4:
    sequence_numbers:
      10: # Mikrotik Discovery Protocol
        action: "deny udp any eq 5678 host 255.255.255.255 eq 5678"
      500: # Tear down link local BGP
        action: "deny tcp 206.80.238.0/24 eq bgp 206.80.238.0/24"
      510:
        action: "deny tcp 206.80.238.0/24 206.80.238.0/24 eq bgp"
      1000:
        action: "ip permit any any"
  acl-qos-tc0-v4: # Scavenger class
    sequence_numbers:
      10:
        action: "permit ip any any dscp cs1"
      20:
        action: "permit ip any any dscp 1"
      30:
        action: "permit ip any any dscp 2"
      40:
        action: "permit ip any any dscp af11"
      50:
        action: "permit ip any any dscp af12"
      60:
        action: "permit ip any any dscp af13"
      70:
        action: "permit tcp any any eq rsync"
      80:
        action: "permit tcp any eq rsync any"
      90:
        action: "permit tcp any any eq ftp-data"
      100:
        action: "permit tcp any eq ftp-data any"
      110:
        action: "permit tcp any any eq smtp"
      120:
        action: "permit tcp any eq smtp any"
      130: # CHARGEN DDoS
        action: "permit udp any eq 19 any"
      140: # SUNRPC DDoS
        action: "permit udp any eq 111 any"
      150: # SNMP DDoS
        action: "permit udp any eq 161 any"
      160: # LDAP DDoS
        action: "permit udp any eq 389 any"
      170: # SSDP DDoS
        action: "permit udp any eq 1900 any"
      180: # ARMS DDoS
        action: "permit udp any eq 3283 any"
      190: # WS-Discovery DDoS
        action: "permit udp any eq 3702 any"
      200: # memcached DDoS
        action: "permit udp any eq 11211 any"
      210: # DHCPDiscover DVR DDoS
        action: "permit udp any eq 37810 any"
      220: # UDP Fragment Attacks
        action: "permit udp any any fragments"
      230: # Internet Archive S3 load-balancer
        action: "permit ip any host 207.241.239.10"
      240: # Internet Archive S3 load-balancer
        action: "permit ip any host 207.241.239.246"

  acl-qos-tc5-v4: # Express Forwarding
    sequence_numbers:
      10:
        action: "permit ip any any dscp ef"
      20:
        action: "permit ip any any dscp cs5"
      30:
        action: "permit udp any any eq domain"
      40:
        action: "permit udp any eq domain any"
      50:
        action: "permit tcp any any eq domain"
      60:
        action: "permit tcp any eq domain any"
      70:
        action: "permit udp any any eq ntp"
      80:
        action: "permit udp any eq ntp any"

  acl-qos-tc6-v4: # IXP control plane
    sequence_numbers:
      10:
        action: "permit tcp 206.80.238.0/24 eq bgp 206.80.238.0/24"
      20:
        action: "permit tcp 206.80.238.0/24 206.80.238.0/24 eq bgp"

ipv6_access_lists:
  acl-protect-ixp-v6:
    sequence_numbers:
      10: # Router Solicitation
        action: "deny icmpv6 any any 133"
      20: # Router Advertisement
        action: "deny icmpv6 any any 134"
      1000:
        action: "ipv6 permit any any"
  acl-bcp214-v6:
    sequence_numbers:
      10: # Router Solicitation
        action: "deny icmpv6 any any 133"
      20: # Router Advertisement
        action: "deny icmpv6 any any 134"
      500:
        action: "deny tcp 2001:504:91::/64 eq bgp 2001:504:91::/64"
      510:
        action: "deny tcp 2001:504:91::/64 2001:504:91::/64 eq bgp"
      1000:
        action: "ip permit any any"
  acl-qos-tc0-v6: # Scavenger Class
    sequence_numbers:
      10:
        action: "permit ipv6 any any dscp cs1"
      20:
        action: "permit ipv6 any any dscp 1"
      30:
        action: "permit ipv6 any any dscp 2"
      31:
        action: "permit ipv6 any any dscp af11"
      32:
        action: "permit ipv6 any any dscp af12"
      33:
        action: "permit ipv6 any any dscp af13"
      40:
        action: "permit tcp any any eq rsync"
      50:
        action: "permit tcp any eq rsync any"
      60:
        action: "permit tcp any any eq ftp-data"
      70:
        action: "permit tcp any eq ftp-data any"
      80:
        action: "permit tcp any any eq smtp"
      90:
        action: "permit tcp any eq smtp any"
      100: # CHARGEN DDoS
        action: "permit udp any eq 19 any"
      110: # SUNRPC DDoS
        action: "permit udp any eq 111 any"
      120: # SNMP DDoS
        action: "permit udp any eq 161 any"
      130: # LDAP DDoS
        action: "permit udp any eq 389 any"
      140: # SSDP DDoS
        action: "permit udp any eq 1900 any"
      150: # ARMS DDoS
        action: "permit udp any eq 3283 any"
      160: # WS-Discovery DDoS
        action: "permit udp any eq 3702 any"
      170: # memcached DDoS
        action: "permit udp any eq 11211 any"
      180: # DHCPDiscover DVR DDoS
        action: "permit udp any eq 37810 any"
      190: # UDP Fragment Attacks
        action: "permit 44 any any"
  acl-qos-tc5-v6: # Express Forwarding
    sequence_numbers:
      10:
        action: "permit ipv6 any any dscp ef"
      20:
        action: "permit ipv6 any any dscp cs5"
      30:
        action: "permit udp any any eq domain"
      40:
        action: "permit udp any eq domain any"
      50:
        action: "permit tcp any any eq domain"
      60:
        action: "permit tcp any eq domain any"
      70:
        action: "permit udp any any eq ntp"
      80:
        action: "permit udp any eq ntp any"
  acl-qos-tc6-v6: # IXP control plane
    sequence_numbers:
      10: # Router Solicitation
        action: "permit icmpv6 any any 135"
      20: # Router Advertisement
        action: "permit icmpv6 any any 136"
      30:
        action: "permit tcp 2001:504:91::/64 eq bgp 2001:504:91::/64"
      40:
        action: "permit tcp 2001:504:91::/64 2001:504:91::/64 eq bgp"

mac_access_lists:
  - name: acl-protect-ixp-mac
    entries:
      - description: "Allow arp"
        action: "permit any ffff.ffff.ffff 0000.0000.0000 arp"
      - description: "Allow IPv6 NS"
        action: "permit any 3333.ff00.0000 0000.00ff.ffff"
      - description: "Block all other broad/multicast"
        action: "deny any 0001.0000.0000 fffe.ffff.ffff"
      - description: "Cisco Discovery Protocol (CDP)"
        action: "deny any 01:00:0c:cc:cc:cc 00:00:00:00:00:00"
      - description: "Spanning Tree of both flavors"
        action: "deny any 01:80:c2:00:00:00 00:00:00:00:00:00"
      - action: "deny any 01:00:0c:cc:cc:cd 00:00:00:00:00:00"
      - description: "Maintenance Operation Protocol (MOP)"
        action: "deny any ab:00:00:02:00:00 00:00:00:00:00:00"
      - action: "permit any any"

qos_profiles:
  qprof_fcix:
    policy_map: pmap_fcix
    tx_queues:
      5:
        priority: no priority
        bandwidth_percent: 19
      1:
        bandwidth_percent: 80
      0:
        bandwidth_percent: 1
  qprof_fcix_uplink:
    tx_queues:
      5:
        priority: no priority
        bandwidth_percent: 19
      1:
        bandwidth_percent: 80
      0:
        bandwidth_percent: 1

policy_maps:
  qos:
    pmap_fcix:
      classes:
        cmap_tc6_v4:
          set:
            traffic_class: 6
        cmap_tc6_v6:
          set:
            traffic_class: 6
        cmap_tc5_v4:
          set:
            traffic_class: 5
        cmap_tc5_v6:
          set:
            traffic_class: 5
        cmap_tc0_v4:
          set:
            traffic_class: 0
        cmap_tc0_v6:
          set:
            traffic_class: 0

class_maps:
  qos:
    cmap_tc6_v4:
      ip:
        access_group: acl_qos_tc6_v4
    cmap_tc6_v6:
      ipv6:
        access_group: acl_qos_tc6_v6
    cmap_tc5_v4:
      ip:
        access_group: acl_qos_tc5_v4
    cmap_tc5_v6:
      ipv6:
        access_group: acl_qos_tc5_v6
    cmap_tc0_v4:
      ip:
        access_group: acl_qos_tc0_v4
    cmap_tc0_v6:
      ipv6:
        access_group: acl_qos_tc0_v6
