---

port_profiles:
  FCIX_PROD:
    mode: access
    vlans: "70"
    qos_profile: qprof_fcix
    storm_control:
      broadcast:
        level: 0.01
      multicast:
        level: 0.01
    structured_config:
      access_group_in: acl-protect-ixp-v4
      ipv6_access_group_in: acl-protect-ixp-v6
      mac_access_group_in: acl-protect-ixp-mac

  FCIX_PROV:
    mode: access
    vlans: "71"
    qos_profile: qprof_fcix
    storm_control:
      broadcast:
        level: 0.01
      multicast:
        level: 0.01
    structured_config:
      access_group_in: acl-protect-ixp-v4
      ipv6_access_group_in: acl-protect-ixp-v6
      mac_access_group_out: acl-protect-ixp-mac

routers:
  AS7247:
    rack: HEFMT2_1400.06.50
    adapters:
      - profile: FCIX_PROV
        switch_ports: [ Ethernet3]
        switches: [ SW4.FMT2.FCIX.NET ]
        endpoint_ports: [ 'Mojo Networks' ]

  AS7034:
    rack: HEFMT2_1400.08.43
    adapters:
      - profile: FCIX_PROD
        switch_ports: [ Ethernet1 ]
        switches: [ SW3.FMT2.FCIX.NET ]
        endpoint_ports: [ 'KWF' ]

