---

port_profiles:
  FCIX_GENERIC:
    mode: access
    qos_profile: qprof_fcix_peer
    storm_control:
      broadcast:
        level: 0.01
      multicast:
        level: 0.01
    structured_config:
      access_group_in: acl-protect-ixp-v4
      ipv6_access_group_in: acl-protect-ixp-v6
      mac_access_group_in: acl-protect-ixp-mac
      spanning_tree_bpdufilter: enabled
    raw_eos_cli: |
        switchport port-security
    port_channel:
      structured_config:
        access_group_in: acl-protect-ixp-v4
        ipv6_access_group_in: acl-protect-ixp-v6
        mac_access_group_in: acl-protect-ixp-mac
        spanning_tree_bpdufilter: enabled
      raw_eos_cli: |
          switchport port-security

  FCIX_PROD:
    parent_profile: FCIX_GENERIC
    vlans: "70"

  FCIX_PROV:
    parent_profile: FCIX_GENERIC
    vlans: "71"

routers:

  AS7034:
    adapters:
      - profile: FCIX_PROD
        switch_ports: [ Ethernet5/1 ]
        switches: [ CORE1.FMT2.FCIX.NET ]
        _peer_name: 'PhirePhly Design'
  AS6939:
    adapters:
      - profile: FCIX_PROD
        switch_ports: [ Ethernet9/1 ]
        switches: [ CORE1.FMT2.FCIX.NET ]
        _peer_name: 'Hurricane Electric'
        port_channel:
          mode: active
  AS26073:
    adapters:
      - profile: FCIX_PROD
        switch_ports: [ Ethernet11/1 ]
        switches: [ CORE1.FMT2.FCIX.NET ]
        _peer_name: 'Cofractal'
        port_channel:
          mode: active
  AS26073B:
    adapters:
      - profile: FCIX_PROD
        switch_ports: [ Ethernet11/1 ]
        switches: [ CORE2.FMT2.FCIX.NET ]
        _peer_name: 'Cofractal'
        port_channel:
          mode: active




  AS55651:
    adapters:
      - profile: FCIX_PROD
        switch_ports: [Ethernet1, Ethernet2 ]
        switches: [ SW5.FMT2.FCIX.NET, SW5.FMT2.FCIX.NET ]
        _peer_name: 'DBolical'
        port_channel:
          mode: active
  AS7247:
    adapters:
      - profile: FCIX_PROD
        switch_ports: [ Ethernet3 ]
        switches: [ SW5.FMT2.FCIX.NET ]
        _peer_name: 'Mojo'
  AS397715:
    adapters:
      - profile: FCIX_PROD
        switch_ports: [ Ethernet4 ]
        switches: [ SW5.FMT2.FCIX.NET ]
        _peer_name: 'KPFA'
  AS199518:
    adapters:
      - profile: FCIX_PROD
        switch_ports: [ Ethernet5 ]
        switches: [ SW5.FMT2.FCIX.NET ]
        _peer_name: 'Gregory Shapiro'
  AS138398:
    adapters:
      - profile: FCIX_PROD
        switch_ports: [ Ethernet6 ]
        switches: [ SW5.FMT2.FCIX.NET ]
        _peer_name: 'Prodigi'
  AS53616:
    adapters:
      - profile: FCIX_PROD
        switch_ports: [ Ethernet7 ]
        switches: [ SW5.FMT2.FCIX.NET ]
        _peer_name: 'Asymptote Networks'
  AS1734:
    adapters:
      - profile: FCIX_PROD
        switch_ports: [ Ethernet8 ]
        switches: [ SW5.FMT2.FCIX.NET ]
        _peer_name: 'DeLong Consulting'
  "AS34615 Universal Exports":
    adapters:
      - profile: FCIX_PROD
        switch_ports: [ Ethernet9 ]
        switches: [ SW5.FMT2.FCIX.NET ]
  AS32872:
    adapters:
      - profile: FCIX_PROD
        switch_ports: [ Ethernet10 ]
        switches: [ SW5.FMT2.FCIX.NET ]
        _peer_name: 'Difficult Computing'
  AS54746:
    adapters:
      - profile: FCIX_PROD
        switch_ports: [ Ethernet11 ]
        switches: [ SW5.FMT2.FCIX.NET ]
        _peer_name: 'Klazo'
  AS63801:
    adapters:
      - profile: FCIX_PROV
        switch_ports: [ Ethernet12 ]
        switches: [ SW5.FMT2.FCIX.NET ]
        _peer_name: 'DODO KK'
  AS22296:
    adapters:
      - profile: FCIX_PROD
        switch_ports: [ Ethernet13 ]
        switches: [ SW5.FMT2.FCIX.NET ]
        _peer_name: 'Vorsk'
  AS15353:
    adapters:
      - profile: FCIX_PROD
        switch_ports: [ Ethernet14 ]
        switches: [ SW5.FMT2.FCIX.NET ]
        _peer_name: 'Xentain Solutions'
  AS53283:
    adapters:
      - profile: FCIX_PROV
        switch_ports: [ Ethernet15 ]
        switches: [ SW5.FMT2.FCIX.NET ]
        _peer_name: 'Litware LLC'
  AS202365:
    adapters:
      - profile: FCIX_PROV
        switch_ports: [ Ethernet16 ]
        switches: [ SW5.FMT2.FCIX.NET ]
        _peer_name: 'Chronos Teknoloji'
  AS21805:
    adapters:
      - profile: FCIX_PROD
        switch_ports: [ Ethernet17 ]
        switches: [ SW5.FMT2.FCIX.NET ]
        _peer_name: 'Mr. Hamel'
  AS57870:
    adapters:
      - profile: FCIX_PROV
        switch_ports: [ Ethernet18 ]
        switches: [ SW5.FMT2.FCIX.NET ]
        _peer_name: 'UNLIMITED IS LIMITED'
  AS397131:
    adapters:
      - profile: FCIX_PROD
        switch_ports: [ Ethernet19 ]
        switches: [ SW5.FMT2.FCIX.NET ]
        _peer_name: 'Everythink Innovations'
  AS40217:
    adapters:
      - profile: FCIX_PROD
        switch_ports: [ Ethernet20 ]
        switches: [ SW5.FMT2.FCIX.NET ]
        _peer_name: 'The St. Paul Group'
  AS32681:
    adapters:
      - profile: FCIX_PROD
        switch_ports: [ Ethernet21 ]
        switches: [ SW5.FMT2.FCIX.NET ]
        _peer_name: 'Bay Area Mesh'
  AS17008:
    adapters:
      - profile: FCIX_PROD
        switch_ports: [ Ethernet22 ]
        switches: [ SW5.FMT2.FCIX.NET ]
        _peer_name: 'Trnasit Yard'
  AS400919:
    adapters:
      - profile: FCIX_PROD
        switch_ports: [ Ethernet23 ]
        switches: [ SW5.FMT2.FCIX.NET ]
        _peer_name: 'Akradam Networks'
  AS64273:
    adapters:
      - profile: FCIX_PROD
        switch_ports: [ Ethernet24 ]
        switches: [ SW5.FMT2.FCIX.NET ]
        _peer_name: 'Orca Networking Services'
  AS18526:
    adapters:
      - profile: FCIX_PROV
        switch_ports: [ Ethernet25 ]
        switches: [ SW5.FMT2.FCIX.NET ]
        _peer_name: 'DDPS'
  AS52025:
    adapters:
      - profile: FCIX_PROD
        switch_ports: [ Ethernet26 ]
        switches: [ SW5.FMT2.FCIX.NET ]
        _peer_name: 'ParadoxNetworks Limited'
  "AS23428 ServerForge":
    adapters:
      - profile: FCIX_PROD
        switch_ports: [ Ethernet27 ]
        switches: [ SW5.FMT2.FCIX.NET ]
  "AS30640 Etheric Networks":
    adapters:
      - profile: FCIX_PROD
        switch_ports: [ Ethernet28 ]
        switches: [ SW5.FMT2.FCIX.NET ]
  "AS25820 IT7 Networks":
    adapters:
      - profile: FCIX_PROD
        switch_ports: [ Ethernet29 ]
        switches: [ SW5.FMT2.FCIX.NET ]
  "AS56328 VNP DIGITAL":
    adapters:
      - profile: FCIX_PROV
        switch_ports: [ Ethernet30 ]
        switches: [ SW5.FMT2.FCIX.NET ]
  "AS21903 Arnhem Networks":
    adapters:
      - profile: FCIX_PROD
        switch_ports: [ Ethernet31 ]
        switches: [ SW5.FMT2.FCIX.NET ]
  "AS40081 Hexium Hosting":
    adapters:
      - profile: FCIX_PROD
        switch_ports: [ Ethernet32 ]
        switches: [ SW5.FMT2.FCIX.NET ]
  "AS12077 Subconscious":
    adapters:
      - profile: FCIX_PROV
        switch_ports: [ Ethernet33 ]
        switches: [ SW5.FMT2.FCIX.NET ]
  "AS31788 Poppy Inc":
    adapters:
      - profile: FCIX_PROD
        switch_ports: [ Ethernet34 ]
        switches: [ SW5.FMT2.FCIX.NET ]
  "AS401117 EQM Holdings":
    adapters:
      - profile: FCIX_PROD
        switch_ports: [ Ethernet35 ]
        switches: [ SW5.FMT2.FCIX.NET ]
  "AS153466 Counterfate":
    adapters:
      - profile: FCIX_PROV
        switch_ports: [ Ethernet36 ]
        switches: [ SW5.FMT2.FCIX.NET ]
  "AS27180 Ace Tomato":
    adapters:
      - profile: FCIX_PROD
        switch_ports: [ Ethernet37 ]
        switches: [ SW5.FMT2.FCIX.NET ]
  "AS893 Ninja-IX":
    adapters:
      - profile: FCIX_PROD
        switch_ports: [ Ethernet38 ]
        switches: [ SW5.FMT2.FCIX.NET ]
  "AS46577 HalNet":
    adapters:
      - profile: FCIX_PROD
        switch_ports: [ Ethernet39 ]
        switches: [ SW5.FMT2.FCIX.NET ]



  AS32621:
    adapters:
      - switch_ports: [ Ethernet46 ]
        switches: [ SW4.FMT2.FCIX.NET ]
        endpoint_ports: [ 'N/A' ]
        _peer_name: 'MN VoIP'
        mode: trunk
        vlans: "70-72,1000"
        qos_profile: qprof_fcix_peer

  AS32097:
    adapters:
      - switch_ports: [ Ethernet47 ]
        switches: [ SW4.FMT2.FCIX.NET ]
        endpoint_ports: [ 'N/A' ]
        _peer_name: 'Wholesale Internet'
        mode: trunk
        vlans: "70,1001"
        qos_profile: qprof_fcix_peer
        structured_config:
          access_group_in: acl-protect-ixp-v4
          ipv6_access_group_in: acl-protect-ixp-v6
          mac_access_group_in: acl-protect-ixp-mac

  SW3.FMT2.FCIX.NET:
    rack: HEFMT2_1400.06.50
    adapters:
      - switch_ports: [ Ethernet32/1 ]
        switches: [ CORE1.FMT2.FCIX.NET ]
        endpoint_ports: [ 'Legacy L2 portal' ]
        _peer_name: 'SW3'
        mode: trunk
        vlans: "10,11,20,21,30,42,43,60,70,71,72,80"
        qos_profile: qprof_fcix_peer
        structured_config:
          speed: forced 40g
          spanning_tree_bpdufilter: enabled

