---

port_profiles:
  FCIX_GENERIC:
    mode: access
    qos_profile: qprof_fcix_peer
    storm_control:
      broadcast:
        level: 0.01
      multicast:
        level: 0.01
    structured_config:
      access_group_in: acl-protect-ixp-v4
      ipv6_access_group_in: acl-protect-ixp-v6
      mac_access_group_in: acl-protect-ixp-mac
    raw_eos_cli: |
        switchport port-security
    port_channel:
      structured_config:
        access_group_in: acl-protect-ixp-v4
        ipv6_access_group_in: acl-protect-ixp-v6
        mac_access_group_in: acl-protect-ixp-mac
      raw_eos_cli: |
          switchport port-security
    endpoint_ports: [ 'N/A', 'N/A' ]

  FCIX_PROD:
    parent_profile: FCIX_GENERIC
    vlans: "70"

  FCIX_PROV:
    parent_profile: FCIX_GENERIC
    vlans: "71"

routers:
  AS53988:
    adapters:
      - profile: FCIX_PROD
        switch_ports: [ Ethernet1 ]
        switches: [ SW3.FMT2.FCIX.NET ]
        endpoint_ports: [ 'Digital Desert' ]

  AS58057:
    adapters:
      - profile: FCIX_PROD
        switch_ports: [ Ethernet2 ]
        switches: [ SW3.FMT2.FCIX.NET ]
        endpoint_ports: [ 'Securebit AG' ]

  AS25948:
    adapters:
      - profile: FCIX_PROD
        switch_ports: [ Ethernet3 ]
        switches: [ SW3.FMT2.FCIX.NET ]
        endpoint_ports: [ 'Datablocks' ]

  AS395502:
    adapters:
      - profile: FCIX_PROD
        switch_ports: [ Ethernet4 ]
        switches: [ SW3.FMT2.FCIX.NET ]
        endpoint_ports: [ 'JeffColo' ]

  AS62000:
    adapters:
      - profile: FCIX_PROV
        switch_ports: [ Ethernet5 ]
        switches: [ SW3.FMT2.FCIX.NET ]
        endpoint_ports: [ 'Netrix SAS' ]

  AS6556:
    adapters:
      - profile: FCIX_PROD
        switch_ports: [ Ethernet6 ]
        switches: [ SW3.FMT2.FCIX.NET ]
        endpoint_ports: [ 'Airgapped' ]

  AS397460:
    adapters:
      - profile: FCIX_PROD
        switch_ports: [ Ethernet7 ]
        switches: [ SW3.FMT2.FCIX.NET ]
        peer_name: 'BayNIC'






  AS26073:
    adapters:
      - profile: FCIX_PROD
        switch_ports: [Ethernet1, Ethernet2 ]
        switches: [ SW4.FMT2.FCIX.NET, SW4.FMT2.FCIX.NET ]
        endpoint_ports: [ 'Cofractal', 'Cofractal' ]
        peer_name: 'Cofractal'
        port_channel:
          mode: active

  AS32098:
    adapters:
      - switch_ports: [ Ethernet46 ]
        switches: [ SW4.FMT2.FCIX.NET ]
        endpoint_ports: [ 'N/A' ]
        peer_name: 'MN VoIP'
        mode: trunk
        vlans: "70-72,1000"
        qos_profile: qprof_fcix_peer

  AS32097:
    adapters:
      - switch_ports: [ Ethernet47 ]
        switches: [ SW4.FMT2.FCIX.NET ]
        endpoint_ports: [ 'N/A' ]
        peer_name: 'Wholesale Internet'
        mode: trunk
        vlans: "70,1001"
        qos_profile: qprof_fcix_peer
        structured_config:
          access_group_in: acl-protect-ixp-v4
          ipv6_access_group_in: acl-protect-ixp-v6
          mac_access_group_in: acl-protect-ixp-mac

  SW1.FMT1.FCIX.NET:
    rack: HEFMT2_1400.06.50
    adapters:
      - switch_ports: [ Ethernet48 ]
        switches: [ SW4.FMT2.FCIX.NET ]
        endpoint_ports: [ 'Trunk to FMT1' ]
        peer_name: 'FMT1 Dark Fiber'
        mode: trunk
        vlans: "10,11,20,21,30,42,43,60,70,71,72,80"
        qos_profile: qprof_fcix_peer
