---

port_profiles:
  FCIX_GENERIC:
    mode: access
    qos_profile: qprof_fcix_peer
    storm_control:
      broadcast:
        level: 0.01
      multicast:
        level: 0.01
    structured_config:
      access_group_in: acl-protect-ixp-v4
      ipv6_access_group_in: acl-protect-ixp-v6
      mac_access_group_in: acl-protect-ixp-mac
    raw_eos_cli: |
        switchport port-security
    port_channel:
      structured_config:
        access_group_in: acl-protect-ixp-v4
        ipv6_access_group_in: acl-protect-ixp-v6
        mac_access_group_in: acl-protect-ixp-mac
      raw_eos_cli: |
          switchport port-security
    endpoint_ports: [ 'N/A', 'N/A' ]

  FCIX_PROD:
    parent_profile: FCIX_GENERIC
    vlans: "70"

  FCIX_PROV:
    parent_profile: FCIX_GENERIC
    vlans: "71"

routers:

  AS7034:
    adapters:
      - profile: FCIX_PROD
        switch_ports: [ Ethernet5/1 ]
        switches: [ CORE1.FMT2.FCIX.NET ]
        peer_name: 'PhirePhly Design'
  AS6939:
    adapters:
      - profile: FCIX_PROD
        switch_ports: [ Ethernet9/1 ]
        switches: [ CORE1.FMT2.FCIX.NET ]
        peer_name: 'Hurricane Electric'
  AS7247:
    adapters:
      - profile: FCIX_PROD
        switch_ports: [ Ethernet3 ]
        switches: [ SW5.FMT2.FCIX.NET ]
        peer_name: 'Mojo'




  AS55651:
    adapters:
      - profile: FCIX_PROD
        switch_ports: [Ethernet1, Ethernet2 ]
        switches: [ SW5.FMT2.FCIX.NET, SW5.FMT2.FCIX.NET ]
        peer_name: 'DBolical'
        port_channel:
          mode: active

  AS32621:
    adapters:
      - switch_ports: [ Ethernet46 ]
        switches: [ SW4.FMT2.FCIX.NET ]
        endpoint_ports: [ 'N/A' ]
        peer_name: 'MN VoIP'
        mode: trunk
        vlans: "70-72,1000"
        qos_profile: qprof_fcix_peer

  AS32097:
    adapters:
      - switch_ports: [ Ethernet47 ]
        switches: [ SW4.FMT2.FCIX.NET ]
        endpoint_ports: [ 'N/A' ]
        peer_name: 'Wholesale Internet'
        mode: trunk
        vlans: "70,1001"
        qos_profile: qprof_fcix_peer
        structured_config:
          access_group_in: acl-protect-ixp-v4
          ipv6_access_group_in: acl-protect-ixp-v6
          mac_access_group_in: acl-protect-ixp-mac

  SW3.FMT2.FCIX.NET:
    rack: HEFMT2_1400.06.50
    adapters:
      - switch_ports: [ Ethernet32/1 ]
        switches: [ CORE1.FMT2.FCIX.NET ]
        endpoint_ports: [ 'Legacy L2 portal' ]
        peer_name: 'SW3'
        mode: trunk
        vlans: "10,11,20,21,30,42,43,60,70,71,72,80"
        qos_profile: qprof_fcix_peer
        structured_config:
          speed: forced 40g

