---

port_profiles:
  FCIX_GENERIC:
    mode: access
    qos_profile: qprof_fcix
    storm_control:
      broadcast:
        level: 0.01
      multicast:
        level: 0.01
    structured_config:
      access_group_in: acl-protect-ixp-v4
      ipv6_access_group_in: acl-protect-ixp-v6
      mac_access_group_in: acl-protect-ixp-mac
    raw_eos_cli: |
        switchport port-security
    port_channel:
      structured_config:
        access_group_in: acl-protect-ixp-v4
        ipv6_access_group_in: acl-protect-ixp-v6
        mac_access_group_in: acl-protect-ixp-mac
      raw_eos_cli: |
          switchport port-security

  FCIX_PROD:
    parent_profile: FCIX_GENERIC
    vlans: "70"

  FCIX_PROV:
    parent_profile: FCIX_GENERIC
    vlans: "71"

routers:
  AS7247:
    rack: HEFMT2_1400.06.50
    adapters:
      - profile: FCIX_PROV
        switch_ports: [ Ethernet3]
        switches: [ SW3.FMT2.FCIX.NET ]
        endpoint_ports: [ 'Mojo Networks' ]

  AS7034:
    rack: HEFMT2_1400.08.43
    adapters:
      - profile: FCIX_PROD
        switch_ports: [ Ethernet1 ]
        switches: [ SW3.FMT2.FCIX.NET ]

  AS26073:
    adapters:
      - profile: FCIX_PROD
        switch_ports: [Ethernet2, Ethernet3 ]
        switches: [ SW3.FMT2.FCIX.NET, SW3.FMT2.FCIX.NET ]
        endpoint_ports: [ 'Cofractal', 'Cofractal' ]
        peer_name: 'Cofractal'
        port_channel:
          mode: active

